# Generated by Django 5.0.4 on 2024-04-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default='', max_length=15, verbose_name='Confirm Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='', max_length=20, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='1996-12-20', verbose_name='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=10, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=15, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.IntegerField(default='1250', verbose_name='Postal Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.TextField(blank=True, verbose_name='Profile of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_conditions',
            field=models.BooleanField(default=True, verbose_name='Terms & Conditions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(default='', verbose_name='Website URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=15, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, unique=True, verbose_name='User Name'),
        ),
    ]
