# Generated by Django 5.0.4 on 2024-04-30 06:11

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_confirm_password_user_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='User Name')),
                ('password', models.CharField(max_length=15, verbose_name='Password')),
                ('confirm_password', models.CharField(max_length=15, verbose_name='Confirm Password')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('country', models.CharField(max_length=20, verbose_name='Country')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('postal_code', models.IntegerField(verbose_name='Postal Code')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('profile', models.TextField(blank=True, verbose_name='Profile of User')),
                ('website_url', models.URLField(verbose_name='Website URL')),
                ('terms_conditions', models.BooleanField(verbose_name='Terms & Conditions')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='terms_conditions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website_url',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
