# Generated by Django 5.0.4 on 2024-04-30 07:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_registeruser_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='favwebsite_url',
            field=models.CharField(default='', max_length=256, validators=[accounts.models.validate_favwebsiteurl]),
            preserve_default=False,
        ),
    ]
